### ISSUE TITLE
Training activity classification requires Intel HD 515 Graphics or later. 

### ISSUE THREAD

**Issue by Android-Dheeraj** [skafos/example-ml-apps#9]
![Screenshot 2020-03-17 at 1 21 35 PM](https://user-images.githubusercontent.com/19361273/76837454-9be35880-6858-11ea-9e9c-f5ae2d6bf824.png)

**Comment by ianterrell** [comment]
Hi @Android-Dheeraj — thanks for peeking at our work! Unfortunately the issue you write about is native to Create ML, which is an Apple tool. If this is slowing you down I encourage you to tell Apple directly via their new bug reporting tool: https://developer.apple.com/bug-reporting/
